import { UniqueIdentifier, CordaX500Name } from "api/domain/shared/corda";

export class InvoiceState {
    public constructor(
        public readonly linearId?: UniqueIdentifier,
        public readonly owner?: CordaX500Name,
        public readonly buyer?: CordaX500Name,
        public readonly supplier?: CordaX500Name,
        public readonly conductor?: CordaX500Name,
        public readonly invoiceVersion?: string,
        public readonly invoiceVersionDate?: string,
        public readonly tixInvoiceVersion?: number,
        public readonly invoiceNumber?: string,
        public readonly invoiceType?: string,
        public readonly reference?: string,
        public readonly dueDate?: Date,
        public readonly offerId?: number,
        public readonly amount?: string,
        public readonly totalOutstanding?: string,
        public readonly created?: Date,
        public readonly updated?: Date,
        public readonly expectedSettlementDate?: Date,
        public readonly settlementDate?: Date,
        public readonly mandatoryReconciliationDate?: Date,
        public readonly invoiceDate?: Date,
        public readonly status?: string,
        public readonly rejectionReason?: string,
        public readonly eligibleValue?: string,
        public readonly invoicePurchaseValue?: string,
        public readonly tradeDate?: Date,
        public readonly tradePaymentDate?: Date,
        public readonly invoicePayments?: string,
        public readonly invoiceDilutions?: string,
        public readonly cancelled?: boolean,
        public readonly closeDate?: Date,
        public readonly originationNetwork?: string,
        public readonly hash?: string,
        public readonly currency?: string,
        public readonly siteId?: string,
        public readonly purchaseOrderNumber?: string,
        public readonly purchaseOrderId?: string,
        public readonly composerProgramId?: number) {
    }
}
