#!/usr/bin/env bash

# REMEMBER TO CONFIGURE THE STORAGE ACCOUNT NAME TO THE ONE YOU HAVE CREATED IN AZURE
ACCOUNT_NAME="cordastorage2"
ACCOUNT_KEY="BNmXBdzIdGs2ZeIX0YY5uPdYXfQGT/ss5GBoWCRfJvXMvk3b0tk1VPQKqSKuYSHAMZshKuBe5AFEkb0PvohIIQ=="
PREFIX='kubernetes-dynamic-'
declare -a MODULES=("notary" "supplier0" "funder0" )
SHORT_DELAY=4
MEDIUM_DELAY=6
